[package]
name = "va"
version = "0.1.0"
authors = ["Ivan Egorov <vany.egorov@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "0.2.0"
chan = "0.1.18"
chan-signal = "0.1.7"
mio = "0.6"

[build-dependencies]
bindgen = "0.19.0"
