#[derive(Clone, Debug)]
pub enum DescriptorTagDVB {
    NetworkName,
    ServiceList,
    Stuffing,
    SatelliteDeliverySystem,
    CableDeliverySystem,
    VBIData,
    VBITeletext,
    BouquetName,
    Service,
    CountryAvailability,
    Linkage,
    NVODReference,
    TimeShiftedService,
    ShortEvent,
    ExtendedEvent,
    TimeShiftedEvent,
    Component,
    Mosaic,
    StreamIdentifier,
    CAIdentifier,
    Content,
    ParentalRating,
    Teletext,
    Telephone,
    LocalTimeOffset,
    Subtitling,
    TerrestrialDeliverySystem,
    MultilingualNetworkName,
    MultilingualBouquetName,
    MultilingualServiceName,
    MultilingualComponent,
    PrivateDataSpecifier,
    ServiceMove,
    ShortSmoothingBuffer,
    FrequencyList,
    PartialTransportStream,
    DataBroadcast,
    Scrambling,
    DataBroadcastId,
    TransportStream,
    DSNG,
    PDC,
    AC3,
    AncillaryData,
    CellList,
    CellFrequencyLink,
    AnnouncementSupport,
    ApplicationSignalling,
    AdaptationFieldData,
    ServiceIdentifier,
    ServiceAvailability,
    DefaultAuthority,
    RelatedContent,
    TVAId,
    ContentIdentifier,
    TimeSliceFecIdentifier,
    ECMRepetitionRate,
    S2SatelliteDeliverySystem,
    EnhancedAC3,
    DTSDescriptor,
    AAC,
    XAITLocation,
    FTAContentManagement,
    Extension,
}

#[derive(Clone, Debug)]
pub enum DescriptorTag {
    VH2621381811172,
    A1381811172,
    Hierarchy,
    RegistrationPrivate,
    DataStreamAlignment,
    TargetBackgroundGrid,
    VideoWindow,
    CASEMMECMPID,
    ISO639,
    SystemClockExternalReference,
    MultiplexBufferUtilizationBounds,
    CopyrightIdentificationSystemAndReference,
    MaximumBitRate,
    PrivateDataIndicator,
    SmoothingBuffer,
    STDVideoBufferLeakControl,
    IBPVideoIFrameIndicator,
    DSMCCCarouselIdentifier,
    DSMCCAssociationTag,
    DSMCCDeferredAssociationTag,
    DSMCCReserved,
    DSMCCNPTReference,
    DSMCCNPTEndpoint,
    DSMCCStreamMode,
    DSMCCStreamEvent,
    VideoStreamHeaderParametersMPEG4H263Based,
    AudioStreamHeaderParametersMPEG4LOASMultiFormatFramed,
    IODParametersForISOIEC144961,
    SLParametersForISOIEC144961,
    FMCParametersForISOIEC144961,
    ExternalESIdentifierForISOIEC144961,
    MuxCodeForISOIEC144961,
    FMXBufferSizeForISOIEC144961,
    MultiplexBufferForISOIEC144961,
    ContentLabelingForISOIEC144961,
    MetadataPointer,
    Metadata,
    MetadataSTD,
    VideoStreamHeaderParametersForITUTRecH264AndISOIEC1449610,
    ISOIEC1381811IPMPDRM,
    TimingAndHRDForITUTRecH264andISOIEC1449610,
    AudioStreamHeaderParametersForISOIEC138187ADTSAAC,
    FlexMuxTimingForISOIEC144961,
    TextStreamHeaderParametersForISOIEC14496,
    AudioExtensionStreamHeaderParametersForISOIEC144963MPEG4LOASMultiFormatFramed,
    VideoAuxiliaryStreamHeaderParameters,
    VideoScalableStreamHeaderParameters,
    VideoMultiStreamHeaderParameters,
    VideoStreamHeaderParametersForITUTRecT800AndISOIEC15444,
    VideoMultiOperationPointStreamHeaderParameters,
    VideoStereoscopic3DStreamHeaderParametersForITUTRecH262ISOIEC138182AndISOIEC111722,
    ProgramStereoscopic3DInformation,
    VideoStereoscopic3DInformation,

    VideoLANFourCCVideoSizeAndCodecInitializationData,

    // 0x40...0x7F
    DVB(DescriptorTagDVB),

    // 0x00...0x01
    // 0x37...0x3F
    Reserved(u8),

    // 0x80...0x9F | 0xA1...0xCF
    ATSC(u8),

    // 0xD0...0xDF
    ISDB(u8),

    // 0xE0...0xE9
    CableLabs(u8),

    // 0xEA...0xFE
    Other(u8),

    // 0xFF
    Forbidden,
}

impl From<u8> for DescriptorTag {
    fn from(d: u8) -> Self {
        match d {
            0x02 => DescriptorTag::VH2621381811172,
            0x03 => DescriptorTag::A1381811172,
            0x04 => DescriptorTag::Hierarchy,
            0x05 => DescriptorTag::RegistrationPrivate,
            0x06 => DescriptorTag::DataStreamAlignment,
            0x07 => DescriptorTag::TargetBackgroundGrid,
            0x08 => DescriptorTag::VideoWindow,
            0x09 => DescriptorTag::CASEMMECMPID,
            0x0A => DescriptorTag::ISO639,
            0x0B => DescriptorTag::SystemClockExternalReference,
            0x0C => DescriptorTag::MultiplexBufferUtilizationBounds,
            0x0D => DescriptorTag::CopyrightIdentificationSystemAndReference,
            0x0E => DescriptorTag::MaximumBitRate,
            0x0F => DescriptorTag::PrivateDataIndicator,
            0x10 => DescriptorTag::SmoothingBuffer,
            0x11 => DescriptorTag::STDVideoBufferLeakControl,
            0x12 => DescriptorTag::IBPVideoIFrameIndicator,
            0x13 => DescriptorTag::DSMCCCarouselIdentifier,
            0x14 => DescriptorTag::DSMCCAssociationTag,
            0x15 => DescriptorTag::DSMCCDeferredAssociationTag,
            0x16 => DescriptorTag::DSMCCReserved,
            0x17 => DescriptorTag::DSMCCNPTReference,
            0x18 => DescriptorTag::DSMCCNPTEndpoint,
            0x19 => DescriptorTag::DSMCCStreamMode,
            0x1A => DescriptorTag::DSMCCStreamEvent,
            0x1B => DescriptorTag::VideoStreamHeaderParametersMPEG4H263Based,
            0x1C => DescriptorTag::AudioStreamHeaderParametersMPEG4LOASMultiFormatFramed,
            0x1D => DescriptorTag::IODParametersForISOIEC144961,
            0x1E => DescriptorTag::SLParametersForISOIEC144961,
            0x1F => DescriptorTag::FMCParametersForISOIEC144961,
            0x20 => DescriptorTag::ExternalESIdentifierForISOIEC144961,
            0x21 => DescriptorTag::MuxCodeForISOIEC144961,
            0x22 => DescriptorTag::FMXBufferSizeForISOIEC144961,
            0x23 => DescriptorTag::MultiplexBufferForISOIEC144961,
            0x24 => DescriptorTag::ContentLabelingForISOIEC144961,
            0x25 => DescriptorTag::MetadataPointer,
            0x26 => DescriptorTag::Metadata,
            0x27 => DescriptorTag::MetadataSTD,
            0x28 => DescriptorTag::VideoStreamHeaderParametersForITUTRecH264AndISOIEC1449610,
            0x29 => DescriptorTag::ISOIEC1381811IPMPDRM,
            0x2A => DescriptorTag::TimingAndHRDForITUTRecH264andISOIEC1449610,
            0x2B => DescriptorTag::AudioStreamHeaderParametersForISOIEC138187ADTSAAC,
            0x2C => DescriptorTag::FlexMuxTimingForISOIEC144961,
            0x2D => DescriptorTag::TextStreamHeaderParametersForISOIEC14496,
            0x2E => DescriptorTag::AudioExtensionStreamHeaderParametersForISOIEC144963MPEG4LOASMultiFormatFramed,
            0x2F => DescriptorTag::VideoAuxiliaryStreamHeaderParameters,
            0x30 => DescriptorTag::VideoScalableStreamHeaderParameters,
            0x31 => DescriptorTag::VideoMultiStreamHeaderParameters,
            0x32 => DescriptorTag::VideoStreamHeaderParametersForITUTRecT800AndISOIEC15444,
            0x33 => DescriptorTag::VideoMultiOperationPointStreamHeaderParameters,
            0x34 => DescriptorTag::VideoStereoscopic3DStreamHeaderParametersForITUTRecH262ISOIEC138182AndISOIEC111722,
            0x35 => DescriptorTag::ProgramStereoscopic3DInformation,
            0x36 => DescriptorTag::VideoStereoscopic3DInformation,

            0xA0 => DescriptorTag::VideoLANFourCCVideoSizeAndCodecInitializationData,

            0x40 => DescriptorTag::DVB(DescriptorTagDVB::NetworkName),
            0x41 => DescriptorTag::DVB(DescriptorTagDVB::ServiceList),
            0x42 => DescriptorTag::DVB(DescriptorTagDVB::Stuffing),
            0x43 => DescriptorTag::DVB(DescriptorTagDVB::SatelliteDeliverySystem),
            0x44 => DescriptorTag::DVB(DescriptorTagDVB::CableDeliverySystem),
            0x45 => DescriptorTag::DVB(DescriptorTagDVB::VBIData),
            0x46 => DescriptorTag::DVB(DescriptorTagDVB::VBITeletext),
            0x47 => DescriptorTag::DVB(DescriptorTagDVB::BouquetName),
            0x48 => DescriptorTag::DVB(DescriptorTagDVB::Service),
            0x49 => DescriptorTag::DVB(DescriptorTagDVB::CountryAvailability),
            0x4A => DescriptorTag::DVB(DescriptorTagDVB::Linkage),
            0x4B => DescriptorTag::DVB(DescriptorTagDVB::NVODReference),
            0x4C => DescriptorTag::DVB(DescriptorTagDVB::TimeShiftedService),
            0x4D => DescriptorTag::DVB(DescriptorTagDVB::ShortEvent),
            0x4E => DescriptorTag::DVB(DescriptorTagDVB::ExtendedEvent),
            0x4F => DescriptorTag::DVB(DescriptorTagDVB::TimeShiftedEvent),
            0x50 => DescriptorTag::DVB(DescriptorTagDVB::Component),
            0x51 => DescriptorTag::DVB(DescriptorTagDVB::Mosaic),
            0x52 => DescriptorTag::DVB(DescriptorTagDVB::StreamIdentifier),
            0x53 => DescriptorTag::DVB(DescriptorTagDVB::CAIdentifier),
            0x54 => DescriptorTag::DVB(DescriptorTagDVB::Content),
            0x55 => DescriptorTag::DVB(DescriptorTagDVB::ParentalRating),
            0x56 => DescriptorTag::DVB(DescriptorTagDVB::Teletext),
            0x57 => DescriptorTag::DVB(DescriptorTagDVB::Telephone),
            0x58 => DescriptorTag::DVB(DescriptorTagDVB::LocalTimeOffset),
            0x59 => DescriptorTag::DVB(DescriptorTagDVB::Subtitling),
            0x5A => DescriptorTag::DVB(DescriptorTagDVB::TerrestrialDeliverySystem),
            0x5B => DescriptorTag::DVB(DescriptorTagDVB::MultilingualNetworkName),
            0x5C => DescriptorTag::DVB(DescriptorTagDVB::MultilingualBouquetName),
            0x5D => DescriptorTag::DVB(DescriptorTagDVB::MultilingualServiceName),
            0x5E => DescriptorTag::DVB(DescriptorTagDVB::MultilingualComponent),
            0x5F => DescriptorTag::DVB(DescriptorTagDVB::PrivateDataSpecifier),
            0x60 => DescriptorTag::DVB(DescriptorTagDVB::ServiceMove),
            0x61 => DescriptorTag::DVB(DescriptorTagDVB::ShortSmoothingBuffer),
            0x62 => DescriptorTag::DVB(DescriptorTagDVB::FrequencyList),
            0x63 => DescriptorTag::DVB(DescriptorTagDVB::PartialTransportStream),
            0x64 => DescriptorTag::DVB(DescriptorTagDVB::DataBroadcast),
            0x65 => DescriptorTag::DVB(DescriptorTagDVB::Scrambling),
            0x66 => DescriptorTag::DVB(DescriptorTagDVB::DataBroadcastId),
            0x67 => DescriptorTag::DVB(DescriptorTagDVB::TransportStream),
            0x68 => DescriptorTag::DVB(DescriptorTagDVB::DSNG),
            0x69 => DescriptorTag::DVB(DescriptorTagDVB::PDC),
            0x6A => DescriptorTag::DVB(DescriptorTagDVB::AC3),
            0x6B => DescriptorTag::DVB(DescriptorTagDVB::AncillaryData),
            0x6C => DescriptorTag::DVB(DescriptorTagDVB::CellList),
            0x6D => DescriptorTag::DVB(DescriptorTagDVB::CellFrequencyLink),
            0x6E => DescriptorTag::DVB(DescriptorTagDVB::AnnouncementSupport),
            0x6F => DescriptorTag::DVB(DescriptorTagDVB::ApplicationSignalling),
            0x70 => DescriptorTag::DVB(DescriptorTagDVB::AdaptationFieldData),
            0x71 => DescriptorTag::DVB(DescriptorTagDVB::ServiceIdentifier),
            0x72 => DescriptorTag::DVB(DescriptorTagDVB::ServiceAvailability),
            0x73 => DescriptorTag::DVB(DescriptorTagDVB::DefaultAuthority),
            0x74 => DescriptorTag::DVB(DescriptorTagDVB::RelatedContent),
            0x75 => DescriptorTag::DVB(DescriptorTagDVB::TVAId),
            0x76 => DescriptorTag::DVB(DescriptorTagDVB::ContentIdentifier),
            0x77 => DescriptorTag::DVB(DescriptorTagDVB::TimeSliceFecIdentifier),
            0x78 => DescriptorTag::DVB(DescriptorTagDVB::ECMRepetitionRate),
            0x79 => DescriptorTag::DVB(DescriptorTagDVB::S2SatelliteDeliverySystem),
            0x7A => DescriptorTag::DVB(DescriptorTagDVB::EnhancedAC3),
            0x7B => DescriptorTag::DVB(DescriptorTagDVB::DTSDescriptor),
            0x7C => DescriptorTag::DVB(DescriptorTagDVB::AAC),
            0x7D => DescriptorTag::DVB(DescriptorTagDVB::XAITLocation),
            0x7E => DescriptorTag::DVB(DescriptorTagDVB::FTAContentManagement),
            0x7F => DescriptorTag::DVB(DescriptorTagDVB::Extension),

            0x00..=0x01 | 0x37..=0x3F => DescriptorTag::Reserved(d),
            0x80..=0x9F | 0xA1..=0xCF => DescriptorTag::ATSC(d),

            0xD0..=0xDF => DescriptorTag::ISDB(d),

            0xE0..=0xE9 => DescriptorTag::CableLabs(d),

            0xEA..=0xFE => DescriptorTag::Other(d),

            0xFF => DescriptorTag::Forbidden,
        }
    }
}

impl From<DescriptorTag> for u8 {
    fn from(dt: DescriptorTag) -> u8 {
        match dt {
            DescriptorTag::VH2621381811172 => 0x02,
            DescriptorTag::A1381811172 => 0x03,
            DescriptorTag::Hierarchy => 0x04,
            DescriptorTag::RegistrationPrivate => 0x05,
            DescriptorTag::DataStreamAlignment => 0x06,
            DescriptorTag::TargetBackgroundGrid => 0x07,
            DescriptorTag::VideoWindow => 0x08,
            DescriptorTag::CASEMMECMPID => 0x09,
            DescriptorTag::ISO639 => 0x0A,
            DescriptorTag::SystemClockExternalReference => 0x0B,
            DescriptorTag::MultiplexBufferUtilizationBounds => 0x0C,
            DescriptorTag::CopyrightIdentificationSystemAndReference => 0x0D,
            DescriptorTag::MaximumBitRate => 0x0E,
            DescriptorTag::PrivateDataIndicator => 0x0F,
            DescriptorTag::SmoothingBuffer => 0x10,
            DescriptorTag::STDVideoBufferLeakControl => 0x11,
            DescriptorTag::IBPVideoIFrameIndicator => 0x12,
            DescriptorTag::DSMCCCarouselIdentifier => 0x13,
            DescriptorTag::DSMCCAssociationTag => 0x14,
            DescriptorTag::DSMCCDeferredAssociationTag => 0x15,
            DescriptorTag::DSMCCReserved => 0x16,
            DescriptorTag::DSMCCNPTReference => 0x17,
            DescriptorTag::DSMCCNPTEndpoint => 0x18,
            DescriptorTag::DSMCCStreamMode => 0x19,
            DescriptorTag::DSMCCStreamEvent => 0x1A,
            DescriptorTag::VideoStreamHeaderParametersMPEG4H263Based => 0x1B,
            DescriptorTag::AudioStreamHeaderParametersMPEG4LOASMultiFormatFramed => 0x1C,
            DescriptorTag::IODParametersForISOIEC144961 => 0x1D,
            DescriptorTag::SLParametersForISOIEC144961 => 0x1E,
            DescriptorTag::FMCParametersForISOIEC144961 => 0x1F,
            DescriptorTag::ExternalESIdentifierForISOIEC144961 => 0x20,
            DescriptorTag::MuxCodeForISOIEC144961 => 0x21,
            DescriptorTag::FMXBufferSizeForISOIEC144961 => 0x22,
            DescriptorTag::MultiplexBufferForISOIEC144961 => 0x23,
            DescriptorTag::ContentLabelingForISOIEC144961 => 0x24,
            DescriptorTag::MetadataPointer => 0x25,
            DescriptorTag::Metadata => 0x26,
            DescriptorTag::MetadataSTD => 0x27,
            DescriptorTag::VideoStreamHeaderParametersForITUTRecH264AndISOIEC1449610 => 0x28,
            DescriptorTag::ISOIEC1381811IPMPDRM => 0x29,
            DescriptorTag::TimingAndHRDForITUTRecH264andISOIEC1449610 => 0x2A,
            DescriptorTag::AudioStreamHeaderParametersForISOIEC138187ADTSAAC => 0x2B,
            DescriptorTag::FlexMuxTimingForISOIEC144961 => 0x2C,
            DescriptorTag::TextStreamHeaderParametersForISOIEC14496 => 0x2D,
            DescriptorTag::AudioExtensionStreamHeaderParametersForISOIEC144963MPEG4LOASMultiFormatFramed => 0x2E,
            DescriptorTag::VideoAuxiliaryStreamHeaderParameters => 0x2F,
            DescriptorTag::VideoScalableStreamHeaderParameters => 0x30,
            DescriptorTag::VideoMultiStreamHeaderParameters => 0x31,
            DescriptorTag::VideoStreamHeaderParametersForITUTRecT800AndISOIEC15444 => 0x32,
            DescriptorTag::VideoMultiOperationPointStreamHeaderParameters => 0x33,
            DescriptorTag::VideoStereoscopic3DStreamHeaderParametersForITUTRecH262ISOIEC138182AndISOIEC111722 => 0x34,
            DescriptorTag::ProgramStereoscopic3DInformation => 0x35,
            DescriptorTag::VideoStereoscopic3DInformation => 0x36,

            DescriptorTag::VideoLANFourCCVideoSizeAndCodecInitializationData => 0xA0,

            DescriptorTag::DVB(DescriptorTagDVB::NetworkName) => 0x40,
            DescriptorTag::DVB(DescriptorTagDVB::ServiceList) => 0x41,
            DescriptorTag::DVB(DescriptorTagDVB::Stuffing) => 0x42,
            DescriptorTag::DVB(DescriptorTagDVB::SatelliteDeliverySystem) => 0x43,
            DescriptorTag::DVB(DescriptorTagDVB::CableDeliverySystem) => 0x44,
            DescriptorTag::DVB(DescriptorTagDVB::VBIData) => 0x45,
            DescriptorTag::DVB(DescriptorTagDVB::VBITeletext) => 0x46,
            DescriptorTag::DVB(DescriptorTagDVB::BouquetName) => 0x47,
            DescriptorTag::DVB(DescriptorTagDVB::Service) => 0x48,
            DescriptorTag::DVB(DescriptorTagDVB::CountryAvailability) => 0x49,
            DescriptorTag::DVB(DescriptorTagDVB::Linkage) => 0x4A,
            DescriptorTag::DVB(DescriptorTagDVB::NVODReference) => 0x4B,
            DescriptorTag::DVB(DescriptorTagDVB::TimeShiftedService) => 0x4C,
            DescriptorTag::DVB(DescriptorTagDVB::ShortEvent) => 0x4D,
            DescriptorTag::DVB(DescriptorTagDVB::ExtendedEvent) => 0x4E,
            DescriptorTag::DVB(DescriptorTagDVB::TimeShiftedEvent) => 0x4F,
            DescriptorTag::DVB(DescriptorTagDVB::Component) => 0x50,
            DescriptorTag::DVB(DescriptorTagDVB::Mosaic) => 0x51,
            DescriptorTag::DVB(DescriptorTagDVB::StreamIdentifier) => 0x52,
            DescriptorTag::DVB(DescriptorTagDVB::CAIdentifier) => 0x53,
            DescriptorTag::DVB(DescriptorTagDVB::Content) => 0x54,
            DescriptorTag::DVB(DescriptorTagDVB::ParentalRating) => 0x55,
            DescriptorTag::DVB(DescriptorTagDVB::Teletext) => 0x56,
            DescriptorTag::DVB(DescriptorTagDVB::Telephone) => 0x57,
            DescriptorTag::DVB(DescriptorTagDVB::LocalTimeOffset) => 0x58,
            DescriptorTag::DVB(DescriptorTagDVB::Subtitling) => 0x59,
            DescriptorTag::DVB(DescriptorTagDVB::TerrestrialDeliverySystem) => 0x5A,
            DescriptorTag::DVB(DescriptorTagDVB::MultilingualNetworkName) => 0x5B,
            DescriptorTag::DVB(DescriptorTagDVB::MultilingualBouquetName) => 0x5C,
            DescriptorTag::DVB(DescriptorTagDVB::MultilingualServiceName) => 0x5D,
            DescriptorTag::DVB(DescriptorTagDVB::MultilingualComponent) => 0x5E,
            DescriptorTag::DVB(DescriptorTagDVB::PrivateDataSpecifier) => 0x5F,
            DescriptorTag::DVB(DescriptorTagDVB::ServiceMove) => 0x60,
            DescriptorTag::DVB(DescriptorTagDVB::ShortSmoothingBuffer) => 0x61,
            DescriptorTag::DVB(DescriptorTagDVB::FrequencyList) => 0x62,
            DescriptorTag::DVB(DescriptorTagDVB::PartialTransportStream) => 0x63,
            DescriptorTag::DVB(DescriptorTagDVB::DataBroadcast) => 0x64,
            DescriptorTag::DVB(DescriptorTagDVB::Scrambling) => 0x65,
            DescriptorTag::DVB(DescriptorTagDVB::DataBroadcastId) => 0x66,
            DescriptorTag::DVB(DescriptorTagDVB::TransportStream) => 0x67,
            DescriptorTag::DVB(DescriptorTagDVB::DSNG) => 0x68,
            DescriptorTag::DVB(DescriptorTagDVB::PDC) => 0x69,
            DescriptorTag::DVB(DescriptorTagDVB::AC3) => 0x6A,
            DescriptorTag::DVB(DescriptorTagDVB::AncillaryData) => 0x6B,
            DescriptorTag::DVB(DescriptorTagDVB::CellList) => 0x6C,
            DescriptorTag::DVB(DescriptorTagDVB::CellFrequencyLink) => 0x6D,
            DescriptorTag::DVB(DescriptorTagDVB::AnnouncementSupport) => 0x6E,
            DescriptorTag::DVB(DescriptorTagDVB::ApplicationSignalling) => 0x6F,
            DescriptorTag::DVB(DescriptorTagDVB::AdaptationFieldData) => 0x70,
            DescriptorTag::DVB(DescriptorTagDVB::ServiceIdentifier) => 0x71,
            DescriptorTag::DVB(DescriptorTagDVB::ServiceAvailability) => 0x72,
            DescriptorTag::DVB(DescriptorTagDVB::DefaultAuthority) => 0x73,
            DescriptorTag::DVB(DescriptorTagDVB::RelatedContent) => 0x74,
            DescriptorTag::DVB(DescriptorTagDVB::TVAId) => 0x75,
            DescriptorTag::DVB(DescriptorTagDVB::ContentIdentifier) => 0x76,
            DescriptorTag::DVB(DescriptorTagDVB::TimeSliceFecIdentifier) => 0x77,
            DescriptorTag::DVB(DescriptorTagDVB::ECMRepetitionRate) => 0x78,
            DescriptorTag::DVB(DescriptorTagDVB::S2SatelliteDeliverySystem) => 0x79,
            DescriptorTag::DVB(DescriptorTagDVB::EnhancedAC3) => 0x7A,
            DescriptorTag::DVB(DescriptorTagDVB::DTSDescriptor) => 0x7B,
            DescriptorTag::DVB(DescriptorTagDVB::AAC) => 0x7C,
            DescriptorTag::DVB(DescriptorTagDVB::XAITLocation) => 0x7D,
            DescriptorTag::DVB(DescriptorTagDVB::FTAContentManagement) => 0x7E,
            DescriptorTag::DVB(DescriptorTagDVB::Extension) => 0x7F,

            DescriptorTag::Reserved(d) => d,
            DescriptorTag::ATSC(d) => d,

            DescriptorTag::ISDB(d) => d,

            DescriptorTag::CableLabs(d) => d,

            DescriptorTag::Other(d) => d,

            DescriptorTag::Forbidden => 0xFF,
        }
    }
}
