#ifndef __VA_VA__
#define __VA_VA__


typedef enum va_atom_kind_enum VAAtomKind;

enum va_atom_kind_enum {
	VA_ATOM_KIND_MPEGTS_HEADER,
	VA_ATOM_KIND_MPEGTS_ADAPTION,
	VA_ATOM_KIND_MPEGTS_PES,
	VA_ATOM_KIND_MPEGTS_PSI_PAT,
	VA_ATOM_KIND_MPEGTS_PSI_PMT,
	VA_ATOM_KIND_MPEGTS_PSI_SDT,

	VA_ATOM_KIND_H264_SPS,
	VA_ATOM_KIND_H264_PPS,
	VA_ATOM_KIND_H264_AUD,
	VA_ATOM_KIND_H264_SEI,
	VA_ATOM_KIND_H264_SLICE_IDR,
};


#endif /* __VA_VA__ */
