version: "3.6"

x-:
  node: &x-node
    build:
      dockerfile: ./docker/node/Dockerfile
      context: ..
    expose:
      - "7946" # memberlist
    networks:
      - raft-memberlist
    command: [
      "-p", "raft-memberlist-node01",
      # "--vvv"
    ]

services:
  build:
    build:
      dockerfile: ./docker/node/Dockerfile
      context: ..
      target: build
    networks:
      - raft-memberlist
    hostname: raft-memberlist-build
    container_name: raft-memberlist-build

  node01:
    <<: *x-node
    hostname: raft-memberlist-node01
    container_name: raft-memberlist-node01
    command: [
      "-p", "raft-memberlist-node02",
      # "--vvv"
    ]

  node02:
    <<: *x-node
    hostname: raft-memberlist-node02
    container_name: raft-memberlist-node02

  node03:
    <<: *x-node
    hostname: raft-memberlist-node03
    container_name: raft-memberlist-node03

networks:
  raft-memberlist:
    name: raft-memberlist
