i:
  - id: 1
    name: tears-of-steel
    url: udp://239.255.1.1:5500
    if: eth0.33

    metrics:
      - dts
      - pts
      - pcr
      - no-signal
      - missing-pid
      - iat
      - mlr
      - h264-frames
      - PID/ID change, add, remove
      - bitrate

    o:
      - url: file:///tmp/tears-of-steel-1.ts
      - url: /tmp/tears-of-steel-2.ts

  - id: 2
    name: big-buck-bunny
    url: udp://239.255.1.2:5500
    if: eth0.34

    o:
      - url: file:///tmp/big-buck-bunny-1.ts
      - url: /tmp/big-buck-bunny-2.ts
      - url: rtmp://172.16.1.2:5500
      - url: udp://239.255.2.1:5500
      - url: 239.255.2.2:5500

  - id: 3
    name: big-buck-bunny
    url: /tmp/dump-i.ts
    o:
      - url: file:///tmp/dump-o.ts

  - id: 4
    name: RBC
    url: http://online.video.rbc.ru/online/rbctv_480p/index.m3u8

color: true

db:
  path: /var/lib/va/db.vadb

log:
  min-level: trace
  max-level: critical
