#include "mpegts.h"


char* mpegts_es_type_string(MPEGTSESType it) {
	switch(it) {
	case MPEGTS_STREAM_TYPE_RESERVED: return MPEGTS_STREAM_TYPE_RESERVED;
	case MPEGTS_STREAM_TYPE_VIDEO_MPEG1: return MPEGTS_STREAM_TYPE_VIDEO_MPEG1_STR;
	case MPEGTS_STREAM_TYPE_VIDEO_MPEG2: return MPEGTS_STREAM_TYPE_VIDEO_MPEG2_STR;
	case MPEGTS_STREAM_TYPE_AUDIO_MPEG1: return MPEGTS_STREAM_TYPE_AUDIO_MPEG1_STR;
	case MPEGTS_STREAM_TYPE_AUDIO_MPEG2: return MPEGTS_STREAM_TYPE_AUDIO_MPEG2_STR;
	case MPEGTS_STREAM_TYPE_PRIVATE_SECTIONS: return MPEGTS_STREAM_TYPE_PRIVATE_SECTIONS_STR;
	case MPEGTS_STREAM_TYPE_PRIVATE_PES_PACKETS: return MPEGTS_STREAM_TYPE_PRIVATE_PES_PACKETS_STR;
	case MPEGTS_STREAM_TYPE_MHEG: return MPEGTS_STREAM_TYPE_MHEG_STR;
	case MPEGTS_STREAM_TYPE_H222_DSM_CC: return MPEGTS_STREAM_TYPE_H222_DSM_CC_STR;
	case MPEGTS_STREAM_TYPE_AUDIO_AAC_ADTS: return MPEGTS_STREAM_TYPE_AUDIO_AAC_ADTS_STR;
	case MPEGTS_STREAM_TYPE_VIDEO_MPEG4_H263: return MPEGTS_STREAM_TYPE_VIDEO_MPEG4_H263_STR;
	case MPEGTS_STREAM_TYPE_VIDEO_MPEG4_FLEX_MUX: return MPEGTS_STREAM_TYPE_VIDEO_MPEG4_FLEX_MUX_STR;
	case MPEGTS_STREAM_TYPE_VIDEO_H264: return MPEGTS_STREAM_TYPE_VIDEO_H264_STR;
	case MPEGTS_STREAM_TYPE_VIDEO_H265: return MPEGTS_STREAM_TYPE_VIDEO_H265_STR;
	case MPEGTS_STREAM_TYPE_AUIDO_AAC_AES_128_CBC: return MPEGTS_STREAM_TYPE_AUIDO_AAC_AES_128_CBC_STR;
	}

	return "";
}
